# Generated by Django 5.1.2 on 2024-11-04 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_portal1', '0003_subscription'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
